### ISSUE TITLE
urllib2.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by dannyvoid** [akurtovic/InstaRaider#15] opened 2015-07-14 11:53 UTC
I've noticed with profiles containing a LOT of images (and occasionally just regular profiles, randomly) an http error will arise. It seems to be a user-agent issue, but I'm not the greatest at figuring that out. 

Error:

C:\Users\Daniel>instaraider -u katsandcrows
katsandcrows has 2138 posts on Instagram.
Loading Instagram profile...
Saving photos to C:/Users/Daniel/Documents/Ghosts/pyLibrary/katsandcrows/
------
Photos saved so far:
---------10--------20--------30--------40--------50
Traceback (most recent call last):
  File "C:\Users\Daniel\Documents\Ghosts\pyLibrary\instaraider.py", line 199, in <module>
    raider.getPhotos(source, userName)
  File "C:\Users\Daniel\Documents\Ghosts\pyLibrary\instaraider.py", line 152, in getPhotos
    self.savePhoto(photoUrl, photoName)
  File "C:\Users\Daniel\Documents\Ghosts\pyLibrary\instaraider.py", line 116, in savePhoto
    imageData = urllib2.urlopen(imageRequest).read()
  File "C:\Python\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python\lib\urllib2.py", line 397, in open
    response = meth(req, response)
  File "C:\Python\lib\urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python\lib\urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "C:\Python\lib\urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "C:\Python\lib\urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by akurtovic** [comment] 2015-07-16 03:22
Thanks for reporting the issue. I'll look into it to see if I can reproduce it. The most photos I've ever tried to download during testing were profiles with about a thousand posts. But I doubt it has anything to do with the number of photos. I'm curious, was this the entire console log? It looks like it failed before downloading any photos.

**Comment by dannyvoid** [comment] 2015-07-16 03:27
Hey.
Yes this is the entire output. It opened firefox, loaded each image, closed the browser then immediately error'd..

**Comment by akurtovic** [comment] 2015-12-01 04:34
Closing for old age and not enough info to take action.

**Closed by akurtovic** 2015-12-01 04:34 UTC
