### ISSUE TITLE
Only downloading 25 images.

### ISSUE THREAD

**Issue by dannyvoid** [akurtovic/InstaRaider#39] opened 2015-12-21 11:10 UTC
Every time I try to download a full profile (1300 images) with metadata, it stops at 25 images.

**Comment by provolot** [comment] 2015-12-26 08:22
I had this problem, too. It's because the JSON data that Instagram includes in the source only contains 25 images. Fixed in PR #41.

**Comment by akurtovic** [comment] 2015-12-26 16:52
Confirmed that PR #41 fixes this issue. Thanks for the commit @provolot and thanks for reporting this issue @dannyvoid

**Closed by akurtovic** 2015-12-26 16:52 UTC
