### ISSUE TITLE
Not actually downloading

### ISSUE THREAD

**Issue by erasmuswill** [akurtovic/InstaRaider#3] opened 2015-01-18 11:19 UTC
wilhelmerasmus has 6 photos on Instagram.
    Loading Selenium WebDriver...
    Loading Instagram profile...
    ...
    Raiding Instagram...
    Saving photos to ./Images/wilhelmerasmus/
    ------
    Photos saved so far:
    ---------10--------20--------30--------40--------50
    
    ------
    Saved 0 images to ./Images/wilhelmerasmus/
    Saved activity in logfile: ./Images/wilhelmerasmus/wilhelmerasmus.csv

I did a few checks and it seems to be getting the source code fine. On profiles with more photos it scrolls and also seems to get the entire source code. However, it doesn't seem to be able to find the images from the source code.

**Comment by akurtovic** [comment] 2015-01-19 16:32
Not sure why it's not working for you. I tried the same on your Instagram a few times from two different machines and it worked each time. Check output below.

I did just add a check to the code to determine if the profile is private or public. Closing issue for now since I cannot reproduce this.

````
amirs-mbp:InstaRaider dak$ python instaRaider.py -u wilhelmerasmus
wilhelmerasmus has 6 photos on Instagram.
Loading Selenium WebDriver...
Loading Instagram profile...
...
Raiding Instagram...
Saving photos to ./Images/wilhelmerasmus/
------
Photos saved so far:
---------10--------20--------30--------40--------50
######
------
Saved 6 images to ./Images/wilhelmerasmus/
Saved activity in logfile: ./Images/wilhelmerasmus/wilhelmerasmus.csv
````

**Closed by akurtovic** 2015-01-19 16:32 UTC

**Comment by erasmuswill** [comment] 2015-01-21 16:24
@akurtovic what are the requirements for running? I've got the selenium webdriver and don't get any exceptions because of undefined modules or anything.

**Comment by akurtovic** [comment] 2015-01-21 16:47
So, just to be clear, you run it and it the WebDriver Firefox windows pops up, it loads your Instagram profile and says that it's saving the photos, but they are not actually saved?

There's a few issues I can think of, but I would need some more info. First of all, I would try throwing some debug statements in the for loop in getPhotos(). One other thing I didn't think about is that this could fail if you have a slow internet connection, so maybe trying a long sleep time at the end of that for loop. Also, what version of Python are you running? urlretrieve() was deprecated, so you may have to change it to urlopen() (https://docs.python.org/2/library/urllib.html). That's probably a fix I need to go back and make anyway.

Let me know if any of those help and if you locate the issue you're having. I'd like to improve this to make sure nobody else has the same problem.

**Comment by erasmuswill** [comment] 2015-01-22 10:14
@akurtovic exactly, got a 256kibps(2mbps)(down) connection with 0.5mbps upload. I'll try your suggestions. I believe I'm using python2.7 as a default target
