### ISSUE TITLE
no images found?

### ISSUE THREAD

**Issue by flexneck** [akurtovic/InstaRaider#12] opened 2015-06-10 19:15 UTC
without me changing anything (at least on purpose) suddenly this error materialized this morning:

Traceback (most recent call last):
  File "Desktop/instaRaider.py", line 231, in <module>
    count = raider.getImageCount(url)
  File "Desktop/instaRaider.py", line 27, in getImageCount
    count = re.findall(r'\d+', countsCode.group())
AttributeError: 'NoneType' object has no attribute 'group

**Comment by dannyvoid** [comment] 2015-06-10 23:04
It's because Instagram recently went through a redesign, which launched yesterday. A lot of elements have changed, so everything is broken unless the author decides to fix it.

**Comment by flexneck** [comment] 2015-06-10 23:36
that unfortunately makes sense and explains why InstaRaider suddenly could not find any images.

**Comment by akurtovic** [comment] 2015-06-14 01:57
I will try to get this fixed by Monday. Unfortunately there is not much I can do about Instagram redesigning the website, other than to change the CSS selectors each time it happens.

**Comment by flexneck** [comment] 2015-06-14 02:31
I totally understand, i am in no rush, it just was very convenient:)

**Comment by mustjbr** [comment] 2015-06-15 18:42
Thanks for the great script.
I am waiting for the update.

I have this error now:
   File "./instaRaider.py", line 240, in <module>
    count = raider.getImageCount(url)
  File "./instaRaider.py", line 30, in getImageCount
    count = re.findall(r'\d+', countsCode.group())
AttributeError: 'NoneType' object has no attribute 'group'

Mustafa

**Comment by getmax0102** [comment] 2015-06-26 21:57
Thank you very much for code
and i'm waiting for the update
i have same error

**Comment by akurtovic** [comment] 2015-07-07 03:58
I still haven't worked through all of the issues caused by the latest redesign, but InstaRaider is now back to at least somewhat functioning. It will save the first 24 images, which is how many are loaded on the first page. I'll try to get the rest of the profile to load in the coming days.

**Comment by akurtovic** [comment] 2015-07-12 01:49
I have now fixed all the issues that were introduced by the redesign. Along with fixing the errors, I also refactored a lot of the code and removed the ability to specify a number of images to save. I have also update the README to document the new usage. I'm marking this issue as closed. If there are any new bugs or issues that crop up due to these changes, please open a new issue.

**Closed by akurtovic** 2015-07-12 01:49 UTC
